apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: run-command
spec:
  restartPolicy: Never
  containers:
    - name: runner
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/bin/sh", "-c"]
      args: ["$COMMAND"]
      env:
        - name: COMMAND
          value: "{{ .Values.command }}"