apiVersion: v1
kind: Pod
metadata:
  name: {{ .Values.podName }}
  namespace: {{ .Values.namespace }}
  labels:
    app: run-command
spec:
  containers:
    - name: runner
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      imagePullPolicy: {{ .Values.image.pullPolicy }}
      command: ["/bin/sh", "-c", "{{ .Values.command }}"]
    #   args: ["$COMMAND"]
    #   env:
    #     - name: COMMAND
    #       value: "{{ .Values.command }}"